spring:
    application:
        name: vehicles-api
    jpa:
        show-sql: true

maps:
    endpoint: http://localhost:9191
pricing:
    endpoint: http://localhost:8082


eureka:
    client:
        service-url:
            defaultZone: http://localhost:8181/eureka
        fetch-registry: true
        register-with-eureka: true
